TrajectoryPlannerROS:
  max_vel_x: 0.15
  min_vel_x: 0.1
  max_vel_theta: 0.7
  min_in_place_vel_theta: 0.5

  acc_lim_theta: 1.5
  acc_lim_x: 1.0
  acc_lim_y: 0.0

  holonomic_robot: true
  
  xy_goal_tolerance: 0.4
  yaw_goal_tolerance: 0.4
